recipes_website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls'))
]

website/urls.py
from django.urls import path
from . import views

app_name = "website"
urlpatterns = [
    path("", views.index, name="index"),
    path("search", views.search_all_recipes, name="search_all_recipes"),
    path("recipes_es/<str:title>/<str:id>", views.elastic_recipe_page,
         name="elastic-recipe-page"),
    path("recipes/<str:title>-<str:id>", views.recipe_page, name="recipe-page"),
    path("accounts/register", views.register, name="register-page"),
    path("accounts/login/", views.login_page, name="login-page"),
    path("profile", views.profile_page, name="profile-page"),
    path("logout_view", views.logout_view, name="logout-page"),
    path("advanced_search", views.advanced_search, name="advanced-search"),


]

website/models.py
from django.db import models

# Create your models here.


class MealType(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class CuisineType(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class DietType(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class IntoleranceType(models.Model):
    name = models.CharField(max_length=70)

    def __str__(self):
        return self.name


class UserSavedRecipeLink(models.Model):
    user_id = models.CharField(max_length=200, blank=False, null=False)
    recipe_id = models.CharField(max_length=200, blank=False, null=False)

website/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class SearchForm(forms.Form):
    recipe_name = forms.CharField(
        max_length=100, required=False,
        widget=forms.TextInput(attrs={"placeholder": "Search the site", "class": "search-input"}))

    cuisine = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple(
        attrs={"class": "filter-item"}), required=False, label="Cuisine:")

    meal = forms.MultipleChoiceField(

        widget=forms.CheckboxSelectMultiple(
            attrs={"class": "filter-item"}),
        required=False, label="Meal:")

    diet = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple(
            attrs={"class": "filter-item"}),
        required=False, label="Diet:")

    intolerance = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple(
            attrs={"class": "filter-item"}),
        required=False, label="Intolerance:")


class CreateUserForm(UserCreationForm):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ["username", "first_name", "last_name",
                  "email", "password1", "password2"]
        labels = {
            "email": "Email"
        }


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={"class": "login-form"}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"class": "login-form"}))


class AdvancedSearchForm(forms.Form):
    search_input = forms.CharField(
        max_length=200, required=False,
        widget=forms.TextInput(attrs={"placeholder": "Enter any ingredients or dish name", "class": "search-input"}))

website/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from . import utils
from .forms import SearchForm, CreateUserForm, LoginForm, AdvancedSearchForm
from .models import UserSavedRecipeLink, CuisineType, MealType, DietType, IntoleranceType
from django.http import JsonResponse
from sentence_transformers import SentenceTransformer


model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')


def index(request):
    recipes = utils.get_random_recipes(1)
    return render(request, 'website/index.html', {"recipes": recipes})


def search_all_recipes(request):
    user_id = int(request.user.id) if request.user.id else None
    if request.body and request.user.is_authenticated:
        utils.add_recipe_to_saved(request)

    elif request.body and not request.user.is_authenticated:
        return JsonResponse({'redirected': 'true'})

    form = SearchForm(request.GET)

    form.fields["cuisine"].choices = utils.extract_field_choices(CuisineType)
    form.fields["meal"].choices = utils.extract_field_choices(MealType)
    form.fields["diet"].choices = utils.extract_field_choices(DietType)
    form.fields["intolerance"].choices = utils.extract_field_choices(
        IntoleranceType)

    search_result = utils.user_search(request.GET)
    recipe_ids = [recipe["id"] for recipe in search_result]
    recipes_all_info = utils.get_many_recipes_info_by_id(recipe_ids)
    recipes_concise_info = utils.extract_many_recipes_concise_info(
        recipes_all_info, user_id)
    recipes_concise_info = utils.extract_many_recipes_ingredients(
        recipes_concise_info)
    return render(request, 'website/search_all_recipes.html', {"form": form, "recipes": recipes_concise_info})


def advanced_search(request):
    user_id = int(request.user.id) if request.user.id else None
    if request.body and request.user.is_authenticated:
        utils.add_recipe_to_saved(request)

    elif request.body and not request.user.is_authenticated:
        return JsonResponse({'redirected': 'true'})

    form = AdvancedSearchForm(request.GET)
    user_input = request.GET.get("search_input")
    if user_input:
        user_input_vector = model.encode(user_input)
        recipes = utils.get_recipes_from_elastic(user_input_vector)
    else:
        recipes = utils.get_random_recipes_from_elastic()

    return render(request, 'website/advanced_search.html', {"form": form, 'recipes': recipes})


def elastic_recipe_page(request, title, id):
    user_id = int(request.user.id) if request.user.id else None
    recipe = utils.extract_recipe_info_from_elastic_by_id(id)
    if recipe:
        return render(request, "website/elastic_recipe.html", {"recipe": recipe, "title": title})
    else:
        return render(request, 'website/index.html')


def recipe_page(request, title, id):
    user_id = int(request.user.id) if request.user.id else None
    recipe_all_info = utils.get_one_recipe_info_by_id(id)

    recipe_nutrition = utils.get_recipe_nutrition(id)
    recipe_concise_info = utils.extract_recipe_info(recipe_all_info, user_id)

    recipe_concise_info["ingredients"] = utils.extract_recipe_ingredients(
        recipe_concise_info)

    recipe_instructions = utils.get_recipe_instructions(id)

    title_formatted = title.replace("-", " ")
    return render(request, "website/recipe.html", {"values": recipe_nutrition,
                                                   "recipe": recipe_concise_info,
                                                   "instructions": recipe_instructions,
                                                   "title": title_formatted})


def register(request):
    if request.user.is_authenticated:
        return redirect("website:profile-page")

    form = CreateUserForm()

    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("website:login-page")

    return render(request, "website/register.html", {"form": form})


def login_page(request):
    if request.user.is_authenticated:
        return redirect("website:profile-page")

    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect("website:profile-page")
        else:
            messages.info(request, "User name OR password is incorrect")

    form = LoginForm()
    return render(request, "website/login.html", {"form": form})


@login_required
def logout_view(request):
    logout(request)
    return redirect("website:index")


@login_required
def profile_page(request):
    user_id = request.user.id
    user_recipes = UserSavedRecipeLink.objects.filter(user_id=user_id)
    is_profile = True
    if user_recipes:
        recipes_ids = [link.recipe_id for link in user_recipes]
        recipes_all_info = utils.get_many_recipes_info_by_id(recipes_ids)
        recipes_concise_info = utils.extract_many_recipes_concise_info(
            recipes_all_info, user_id)

        return render(request, "website/profile.html", {"recipes": recipes_concise_info,
                                                        "is_profile": is_profile})

    else:
        context = "You don't have any favorite recipes yet"
        return render(request, "website/profile.html", {"recipes": None,
                                                        "context": context,
                                                        "is_profile": is_profile})

website/templates/website/advanced_search.html
{% extends "website/base.html" %}
{% load static %}

{% block title %} 
AI Search
{% endblock %} 

{% block css_files %}
  <link rel="stylesheet" href="{% static "website/advanced_search.css" %}" />
  <link rel="stylesheet" href="{% static "website/includes/add_recipe_btn.css" %}" />

{% endblock %}

{% block content %}
<div class="title-section"> 
    <h1 id="title">Find What <span class="highlight-span">Suits</span> You</h1>
    <p id="tagline">Try our new advanced search powered by artificial intelligence </p>
  </div> 
  <form class="form" action={% url 'website:advanced-search'%} method="GET">
    <div class="search-field"> 
      {{ form.search_input }}
      <input class="search-btn" type="submit" value="Search">
    </div>
</form>

<div class="recipes-group">
  {% for recipe in recipes %}
  <div class="card mb-3">
    <div class="row g-0">
      <div class="col-md-4">
        {% if recipe.image == 'None' %}
        <img src="https://img.staticmb.com/mbcontent/images/crop/uploads/2023/4/ceramic-plates_0_1200.jpg" class="img-fluid rounded-start" alt="dish">
        {% else %}
        
        <img src={{ recipe.image }} class="img-fluid rounded-start" alt="dish">
        {% endif %}
      </div>
      <div class="col-md-8">
        <div class="card-body">
          {% csrf_token %}
          <a class="card-title" href="{% url "website:elastic-recipe-page" title=recipe.title|slugify id=recipe.id %}">{{ recipe.title }}</a>

          <div class="card-text">
            <div class="dropdown">
              <button class="btn dropdown-toggle ingrd-btn" type="button" data-bs-toggle="dropdown" aria-expanded="false">
              {{ recipe.ingredients|length}}  Ingredients</button>
                <ul class="dropdown-menu ingrd-menu">
                  <p class="ingr-title"> INGREDIENTS </p>
                    {% for ingredient in recipe.ingredients%}
                        <li class="ingrd-item">{{ ingredient|capfirst  }}<span class="underscore"></span> {{ ingredient.amount|cut:".0"}} {{ ingredient.unit|lower}}</li>
                    {% endfor %}
                 
                  <a class="btn btn-go-to-recipe" href="{% url "website:elastic-recipe-page" title=recipe.title|slugify id=recipe.id %}" role="button">Go to recipe page</a>
                </ul>
              <span class="pipe">|</span>
            </div>

          </div>
        </div>
        {% if recipe.is_saved %}
        <button class="btn added-recipe">Added to recipe book</button>
        {% else %}
        <button data-recipe-id={{recipe.id}} class="btn add-recipe" id="add" onclick="">Add to recipe book</button>
        {% endif %}
      </div>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock %} 
{% block script %}
  {% include "website/includes/add_recipe_btn.html" %}
{% endblock %}

website/templates/website/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock %}</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;400;500;600&family=Playfair+Display:wght@400;500;600&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://necolas.github.io/normalize.css/latest/normalize.css">
  <link rel="stylesheet" href="{% static "website/base.css" %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  {% block css_files %}{% endblock %}
</head>
<body>
  <header id="main-navigation">
    <h1><a href="{% url "website:index" %}">Recipes</a></h1>
    <div id="header-links">
      <a id="home" href="{% url "website:index" %}">HOME</a>
      <a id="search" href="{% url "website:search_all_recipes" %}">SEARCH</a>
      <a id="advanced_search" href="{% url "website:advanced-search" %}">AI SEARCH</a>
    </div>
      {% if not is_profile%}
        <a id="profile" href="{% url "website:profile-page" %}">Profile</a>
      {% else %}
        <a class="logout" href="{% url "website:logout-page" %}">Log out</a>
      {% endif %}
    {% block header %}
    {% endblock %}
  </header>
  <main>
    {% block content %}
    {% endblock %}
  </main>
  
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
{% block script %}
{% endblock %}
</body>
</html>

website/templates/website/elastic_recipe.html
{% extends "website/base.html" %}
{% load static %}

{% block title %} 
{{title|title}}
{% endblock %} 

{% block css_files %}
  <link rel="stylesheet" href="{% static "website/includes/add_recipe_btn.css" %}" />
  <link rel="stylesheet" href="{% static "website/recipe.css" %}"/>

{% endblock %}

{% block content %}
    <div class="title-section">
        <h1  class="title">{{ title|title }}</h1>
    </div>

    <div class="description">
        <div class="ingrd-menu">
            <ul class="ingrd-menu">
                <p class="ingr-title"> INGREDIENTS </p>
                {% for ingredient in recipe.ingredients%}
                <li class="ingrd-item">{{ ingredient|capfirst }}<span class="underscore"></span></li>
                {% endfor %}
            </ul>
        </div>
        <div class="image-btn-container">
            {% if recipe.image == 'None' %}
            <img class="recipe-img"src="https://img.staticmb.com/mbcontent/images/crop/uploads/2023/4/ceramic-plates_0_1200.jpg" alt="dish" />

            {% else %}
            <img class="recipe-img"src="{{recipe.image}}" alt="dish" />

            {% endif %}

            {% if recipe.is_saved %}
            <button class="btn added-recipe">Added to recipe book</button>
            {% else %}
            <button data-recipe-id={{recipe.id}} class="btn add-recipe" id="add" onclick="">Add to recipe book</button>
            {% endif %}
        </div>
    </div>

    <div class="instructions">
        <p class="instructions-title">RECIPE INSTRUCTIONS</p>
        <ul class="steps">

            {% for step in recipe.instructions%}
            <li class="step">
                <p class="step-number">{{ forloop.counter }}.</p>
                <p class="step-text">{{ step }}</p>
            </li>
            {% endfor %}
        </ul>
    </div>
    

{% endblock %}

{% block script %}
  {% include "website/includes/add_recipe_btn.html" %}
{% endblock %}

website/templates/website/index.html
{% extends "website/base.html" %}
{% load static %}

{% block title %} 
Home
{% endblock %} 

{% block css_files %}
  <link rel="stylesheet" href="{% static "website/index.css" %}" />
  <link rel="stylesheet" href="{% static "website/includes/recipe_card.css" %}" />
{% endblock %}

{% block content %}

    <div class="title-section"> 
        <h1 id="title">Taste  <span class="highlight-span">&</span>  delight</h1>
        <p id="tagline">Unleash Flavorful Moments</p>
    </div> 
    <a class="find-recipe-btn-link" href="{% url "website:search_all_recipes" %}">Find a Recipe</a>


    <div class="image-container">
        <img class="pancakes-img"src="{% static "website/images/pancakes.jpg" %}" alt="pancakes" />
    </div>

    <h2 class="sub_headline">Find Inspiration From Our Offers</h2>


    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% include "website/includes/recipe_card.html" %}
    </div>

{% endblock %}

website/templates/website/login.html
{% extends "website/base.html" %}
{% load static %}

{% block title %} 
Log in
{% endblock %} 

{% block css_files %}
  <link rel="stylesheet" href="{% static "website/login.css" %}" />
{% endblock %}


{% block content %}
<div class="form-wrapper">
  <form class="form" action='' method="POST">
      {% csrf_token %}
      <p class="title">Log in</p>
      {% for field in form %}
          <label class="field-label">{{ field.label }} 
            {{ field }}
          </label>
      {% endfor %}
      <input class="login-btn" type="submit" value="Log in">
      <a class="register-link" href="{% url "website:register-page" %}">Do not have an account</a>

      {% comment %} {% if form.error_messages  %} {% endcomment %}
       {% comment %} {% for field in form %} {% endcomment %}
           {% for message in messages  %} 
              <div class="alert alert-danger">
                   <strong>{{ message|escape }}</strong>
              </div> 
           {% endfor %}
       {% comment %} {% endfor %} {% endcomment %}
    {% comment %} {% endif %} {% endcomment %}
        
  </form>

</div>

{% endblock %} 

website/templates/website/profile.html
{% extends "website/base.html" %}

{% load static %}

{% block title %} 
Profile
{% endblock %} 

{% block css_files %}
  <link rel="stylesheet" href="{% static "website/profile.css" %}" />
  <link rel="stylesheet" href="{% static "website/includes/recipe_card.css" %}"/>
  <link rel="stylesheet" href="{% static "website/base.css" %}"/>
{% endblock %}
{% block content %}
  <div class="title-section">
    {%if not recipes %}
      <h2 class="context">{{context|title}}</h2>
      <h3 class="subcotext">Get To Know Our Treasures </h3>
      <a class="find-recipe-btn-link" href="{% url "website:search_all_recipes" %}">Find a Recipe</a>
    {% else %}
      <h1 class="title">Your Favourite Recipes</h1>
    {% endif %}
  </div>
  <div class="row row-cols-1 row-cols-md-1 g-4">
    {% include "website/includes/recipe_card.html" %}
  </div>
{% endblock %} 

website/templates/website/recipe.html
{% extends "website/base.html" %}
{% load static %}

{% block title %} 
{{title|title}}
{% endblock %} 

{% block css_files %}
  <link rel="stylesheet" href="{% static "website/includes/add_recipe_btn.css" %}" />
  <link rel="stylesheet" href="{% static "website/recipe.css" %}"/>

{% endblock %}

{% block content %}
    <div class="title-section">
        <h1  class="title">{{ title|title }}</h1>
    </div>
    
    <p class="value-header">FOOD ENERGY PER SERVING</p>

    <div class="value-info">    
        {% for value, qnt in values.items %}
        <div class="value">
            <p class="value-desc"> {{ value|upper }} </p>
            <p class="value-qnt"> {{ qnt|cut:"g" }} </p>
            {% if value == "calories"%}
                <p class="value-desc">KCAL</p>
            {% else %}
                <p class="value-desc">GRAMS</p>
            {% endif %}
        </div>
        {% endfor %}
    </div>

    <div class="description">
        <div class="ingrd-menu">
            <ul class="ingrd-menu">
                {% include "website/includes/ingredients.html" %}
            </ul>
        </div>
        <div class="image-btn-container">
            <img class="recipe-img"src="{{recipe.image}}" alt="dish" />
            {% if recipe.is_saved %}
            <button class="btn added-recipe">Added to recipe book</button>
            {% else %}
            <button data-recipe-id={{recipe.id}} class="btn add-recipe" id="add" onclick="">Add to recipe book</button>
            {% endif %}
        </div>
    </div>

    <div class="instructions">
        <p class="instructions-title">RECIPE INSTRUCTIONS</p>
        <ul class="steps">
            {% for step in instructions%}
            <li class="step">
                <span class="step-number">{{ step.number }}</span>
                <p class="step-text">{{ step.step }}</p>
            </li>
            {% endfor %}
        </ul>
    </div>
    

{% endblock %}

{% block script %}
  {% include "website/includes/add_recipe_btn.html" %}
{% endblock %}

website/templates/website/register.html
{% extends "website/base.html" %}
{% load static %}

{% block title %} 
Sign in
{% endblock %} 

{% block css_files %}
  <link rel="stylesheet" href="{% static "website/register.css" %}" />
{% endblock %}

{% block content %}
<div class="form-wrapper">
  <form class="form" action='' method="POST">
      {% csrf_token %}
      <p class="title">Create an account</p>
      {% for field in form %}
          <label class="field-label">{{ field.label }} 
            {{ field }}
          </label>
      {% endfor %}
      <input class="create-account-btn" type="submit" value="Create an account">
      <a class="login-link" href="{% url "website:login-page" %}">Already have an account</a>
      {% if form.errors %}
       {% for field in form %}
           {% for error in field.errors %} 
              <div class="alert alert-danger">
                   <strong>{{ error|escape }}</strong>
              </div>
           {% endfor %}
       {% endfor %}
    {% endif %}
        
  </form>

</div>

{% endblock %} 

website/templates/website/search_all_recipes.html
{% extends "website/base.html" %}
{% load static %}

{% block title %} 
Search
{% endblock %} 

{% block css_files %}
  <link rel="stylesheet" href="{% static "website/search_all_recipes.css" %}" />
  <link rel="stylesheet" href="{% static "website/includes/add_recipe_btn.css" %}" />

{% endblock %}

{% block content %}
  <div class="title-section"> 
    <h1 id="title">Find What <span class="highlight-span">Suits</span> You</h1>
    <p id="tagline">Unleash Flavorful Moments</p>
  </div> 
  <form class="form" action={% url 'website:search_all_recipes'%} method="GET">
        <div class="search-field"> 
          {{ form.recipe_name }}
          <input class="search-btn" type="submit" value="Search">
        </div>
    <div class="checkbox-fields">
      {% for field in form %}
        {% if field.name != "recipe_name" %}
          <div class="fieldWrapper">
            <label class="filter-label">{{ field.label }}</label>
            {{ field }}
          </div>
        {% endif %}
      {% endfor %}
      </div>
   
  </form>

  <div class="recipes-group">
      {% for recipe in recipes %}
      <div class="card mb-3">
        <div class="row g-0">
          <div class="col-md-4">
            <img src={{ recipe.image }} class="img-fluid rounded-start" alt="dish">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              {% csrf_token %}
              <a class="card-title" href="{% url "website:recipe-page" title=recipe.title|slugify id=recipe.id %}">{{ recipe.title }}</a>

              <div class="card-text">
                <div class="dropdown">
                  <button class="btn dropdown-toggle ingrd-btn" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                  {{ recipe.ingredients|length}}  Ingredients</button>
                    <ul class="dropdown-menu ingrd-menu">
                      {% include "website/includes/ingredients.html" %}
                     
                      <a class="btn btn-go-to-recipe" href="{% url "website:recipe-page" title=recipe.title|slugify id=recipe.id %}" role="button">Go to recipe page</a>
                    </ul>
                  <span class="pipe">|</span>
                </div>
                <p>🥗{{ recipe.servings }} servings  ⏱️{{recipe.ready_in_minutes}} minutes</p>
              </div>
            </div>
            {% if recipe.is_saved %}
            <button class="btn added-recipe">Added to recipe book</button>
            {% else %}
            <button data-recipe-id={{recipe.id}} class="btn add-recipe" id="add" onclick="">Add to recipe book</button>
            {% endif %}
          </div>
        </div>
      </div>
      {% endfor %}
  </div>
{% endblock %} 

{% block script %}
  {% include "website/includes/add_recipe_btn.html" %}
{% endblock %}